# Generated by Django 4.2.6 on 2023-10-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
